# .streamlit/secrets.toml
# ここにGoogle Cloudの認証情報を貼り付けます。
# このファイルは絶対に外部（GitHubなど）に公開しないでください！

[connections.gsheets]
spreadsheet = "ここにスプレッドシートのURLまたは名前を入力"

# 以下はGoogle CloudのService Accountキーファイル(JSON)の中身を転記します
type = "service_account"
project_id = "xxx"
private_key_id = "xxx"
private_key = "-----BEGIN PRIVATE KEY----- ... \n"
client_email = "xxx@xxx.iam.gserviceaccount.com"
client_id = "xxx"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/xxx"
